Update MailgunSwiftTransport.php
Changed Swift_Mime_Message to Swift_Mime_SimpleMessage, as Swift_Mime_Message was no longer available in Swiftmailer version 6 which is now used in SilverStripe since 4.9.0.

The error message you will get is:

Fatal error: Could not check compatibility between LeKoala\Mailgun\MailgunSwiftTransport::send(Swift_Mime_Message $message, &$failedRecipients = NULL) and Swift_Transport::send(Swift_Mime_SimpleMessage $message, &$failedRecipients = NULL), because class Swift_Mime_Message is not available in MailgunSwiftTransport.php on line 100